# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    users_directory: '%kernel.project_dir%/public/uploads/users'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.pet:
        class: App\Admin\PetAdmin
        arguments: [ ~, App\Entity\Pet, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Mascotas }

    admin.user:
        class: App\Admin\UserAdmin
        arguments: [ ~, App\Entity\User, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Usuarios }

    admin.clinic:
        class: App\Admin\ClinicAdmin
        arguments: [ ~, App\Entity\Clinic, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Clinicas }