version: '3'

services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_clinic:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - symfony
  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/clinic/
    networks:
      - symfony
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/clinic/
    ports:
      - "80:80"
    networks:
      - symfony

volumes:
  db_clinic:

networks:
  symfony: